sudo: false
language: php

php:
  - 7.3
  - 7.4

before_install:
  - pecl install ast
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover ./tests/coverage/clover.xml
  - vendor/bin/behat

after_success:
  - travis_retry php vendor/bin/php-coveralls -v